apiVersion: v1
kind: ConfigMap
metadata:
  name: alchemiscale-configmap
  namespace: alchemiscale
data:

  # neo4j
  NEO4J_URL: bolt://alchemiscale-neo4j-service:7687

  # api services
  ALCHEMISCALE_API_URL: http://alchemiscale-computeapi-service
  ALCHEMISCALE_COMPUTE_API_URL: http://alchemiscale-clientapi-service

  # jwt
  JWT_EXPIRE_SECONDS: "3600"
  JWT_ALGORITHM: "HS256"

  # ingress placeholder
