apiVersion: v1
kind: ConfigMap
metadata:
  name: alchemiscale-configmap
data:

  # neo4j
  NEO4J_URL: bolt://neo4j-service:7687  # TODO this should just work with 'neo4j-service'

  # api services
  computeAPI_url: computeapi-service
  clientAPI_url: clientapi-service

  # jwt
  JWT_EXPIRE_SECONDS: "3600"
  JWT_ALGORITHM: "HS256"

  # ingress placeholder
