apiVersion: apps/v1
kind: Deployment
metadata:
  name: alchemiscale-clientapi
  namespace: alchemiscale
  labels:
    app: alchemiscale-clientapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alchemiscale-clientapi
  template:
    metadata:
      labels:
        app: alchemiscale-clientapi
    spec:
      initContainers:
      - name: db-init
        image: ghcr.io/openforcefield/alchemiscale-server:0.1.3-3
        envFrom:
          - configMapRef:
              name: alchemiscale-configmap
          - secretRef:
              name: alchemiscale-neo4j-secrets
        args: ["database", "init"]
      containers:
      - name: alchemiscale-clientapi-container
        image: ghcr.io/openforcefield/alchemiscale-server:0.1.3-3
        ports:
        - containerPort: 1840
        envFrom:
          - configMapRef:
              name: alchemiscale-configmap
          - secretRef:
              name: alchemiscale-neo4j-secrets
          - secretRef:
              name: alchemiscale-aws-secrets          
          - secretRef:
              name: alchemiscale-jwt-secrets
        args: ["api", "--host", "0.0.0.0", "--port", "1840", "--workers", "2"]
---
apiVersion: v1
kind: Service
metadata:
  name: alchemiscale-clientapi-service
  namespace: alchemiscale
spec:
  selector:
    app: alchemiscale-clientapi
  ports:
  - port: 1840
    name: http
