apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: #  Set the local storage path for the persistent volume
  storageClassName: neo4j-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-claim
spec:
  storageClassName: neo4j-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:4.4
        envFrom:
          - secretRef:
              name: neo4j-secrets
        ports:
            - name: bolt
              protocol: TCP
              containerPort: 7687
            - name: viewer-http
              protocol: TCP
              containerPort: 7474
        volumeMounts:
          - name: neo4j-data-storage
            mountPath: /var/lib/neo4j/data
      volumes:
        - name: neo4j-data-storage
          persistentVolumeClaim:
            claimName: neo4j-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j
  ports:
  - port: 7687
    name: bolt
  - port: 7474
    name: viewer-http

